version: 0.1.{build}
image: Visual Studio 2019
configuration:
- Release
- Debug
platform: x64
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
build_script:
  - msbuild "C:\projects\essentia\Essentia.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
